collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.9816964
  brandStrength: 0.4828498
  rhythmicContrast: 0.2977846
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  lightness: 0.4790715
typography_spectrum: 0.1423201
layout_spectrum: 0.9844254
name: MAAVI
